### PR TITLE
Fixed accountId to publicKey conversion

### LINKED ISSUE #137: new metadata endpoint internal error when using address
```
{
    "code": "Internal",
    "message": "db.addressToPublicKey is not a function"
}
```

### PR DESCRIPTION
**Pull request by martinayora**
Fixes #137.

### CODE REVIEW

File: rest/src/plugins/metadata/metadataRoutes.js [hunk 1]
```diff
@@ -81,34 +82,56 @@ module.exports = {
 			const pagingOptions = routeUtils.parsePagingArguments(req.params);
 			const ordering = routeUtils.parseArgument(req.params, 'ordering', input => ('id' === input ? 1 : -1));
 
-			return accountIdToPublicKey(type, accountId).then(publicKey =>
-				db.getMetadataWithPagination(
+			return accountIdToPublicKey(type, accountId).then(publicKey => {
+				if (undefined === publicKey) {
```
Comment (Vektrat) [inline rest/src/plugins/metadata/metadataRoutes.js]: if (!publicKey)

File: rest/src/routes/routeUtils.js [hunk 2]
```diff
@@ -322,7 +322,7 @@ const routeUtils = {
 	 * @returns {Promise<Uint8Array>} Account public key.
 	 */
 	addressToPublicKey: (db, accountAddress) => db.addressToPublicKey(accountAddress)
```
Comment (Vektrat) [inline rest/src/routes/routeUtils.js]: i'm not really happy with this behaviour, is the resulting code clean if this function throws an Error (promise failure), and whoever calls it manages the promise rejection?
