### PR TITLE
Fixed incoming transactions by address

### LINKED ISSUE #170: Querying transactions/incoming by address does not work for accounts not present in the blockchain
related to #164 , creating an issue because it is an specific case that _has_ a solution, while we are unsure we can provide a solution for the rest of transaction endpoints

---
modify the db call to always be queried by address instead of publicKey

### PR DESCRIPTION
**Pull request by martinayora**
Fixes #170.

### CODE REVIEW

File: rest/src/routes/accountRoutes.js [hunk 1]
```diff
@@ -74,5 +78,20 @@ module.exports = {
 						.then(transactionSender.sendArray('accountId', res, next)));
 			});
 		});
+
+		server.get('/account/:accountId/transactions/incoming', (req, res, next) => {
```
Comment (Vektrat) [inline rest/src/routes/accountRoutes.js]: i believe we can keep the old logic and just pass an address, we can rename the `accountAddress`/`publicKey` to `account` or similar to generalize
