### PR TITLE
Task/t186 fix duplicate connections

### LINKED ISSUE #186: Ensure only one open connection to API node
Referring to this https://github.com/nemtech/catapult-rest/pull/6 as it is still an issue

Original quote:
> When rest gateway receives a burst of transactions on startup, it will open a new connection for each request as connectionService has not saved the connection while waiting for the verification to complete.

### PR DESCRIPTION
**Pull request by Vektrat**
Fixes #186 (#6), and hopefully the random `Address already in use` failure from tests, though it's just a wild guess

basically added a cached "pending for authentication" object to store connections that have not been authenticated yet since this does not happen until `lease()`, in this window of time if multiple requests are received different connections are spawned with conflicting addresses

### CODE REVIEW

File: rest/src/connection/connectionService.js [hunk 1]
```diff
@@ -65,15 +68,31 @@ module.exports.createConnectionService = (config, connectionFactory, authPromise
...
-			}, reject);
+				return serverConnection;
+			}).catch(err => {
+				if (isPersistent)
+					delete authenticatingConnectionPromises[node];
+
+				// reject and additionally, return the connection for possible queued connections on `authenticatingConnectionPromises`
+				reject(err);
+				throw err;
+			});
```
Comment (Vektrat) [inline rest/src/connection/connectionService.js]: not using `finally` for
```
if (isPersistent)
        delete authenticatingConnectionPromises[node];
```

because the `resolve()` code is executed before the `finally()`s which can lead into conflicts
